### ISSUE TITLE
[feature request] pronunciation and part of speech columns

### ISSUE THREAD

**Issue by omega3** [yakhinvadim/longman-to-anki#182]
Could you please add columns for pronunciation (IPA signs - not sound, for example  /ˈpʌblɪk/ ) and part of speech column. For example - word "public" has two meanings: adjective and noun.
https://www.ldoceonline.com/dictionary/public

**Comment by yakhinvadim** [comment]
This is a good idea.
But I was thinking about this: instead of a table with all the cards, put the slider with the actual cards, exactly how it looks in anki. 
Pros: I could see all the data for one card at once
Cons: I wouldn't be able to see all the cards at once

What do you think?

**Comment by omega3** [comment]
But why? Well to be honest I don't like this idea. Isn't table enough? I think it is good as is, only additional data like pronunciation and part of speech can be added. Unless there are some technical limitations that I am not aware of.

> I could see all the data for one card at once

The same can be seen in online Longman dictionary, so it is easy to predict how the card will look like. 

The biggest advantage of your project is that card can be made in bulk. I prepared for myself a Longman 3000 list. You project gives opportunity to do it fast, instead of copy paste each sentence one by one. My opinion is: keep it this way. 

How about export to csv file instead of creating anki apkg file each time. Or just a button copy table? For me it is even easier to copy from your site and paste to Libreoffice Calc or Excel (or even google spreadsheet) and save as csv (at least when my list is long) because in spreadsheet I can do additional formatting and add native language translation. 

Have a look at example:
https://i.imgur.com/MRXFyjQ.png

This is perfectly enough for me. 

Edit: In case of public noun there is no pronunciation so the field should be left empty. 

(Also sound would be great, so sound file name would be another column, but this is different issue. Sound could be downloaded as zip).

**Comment by yakhinvadim** [comment]
Thank you for giving your thoughts on this, I really appreciate that!

You're right, I haven't thought that the app could be used this way. Well then, I think I should add more columns to the table and add an option to download everything as csv.

I'll also think about working with sounds. This is not trivial to do but would be very useful, so I'll give it a shot.

But again, I'm sorry I can't give estimates yet about when it will be ready. I want to say in a month, but I can't be sure.

**Comment by yakhinvadim** [comment]
Hey @omega3, 
I've added more columns in the tables and a "Download CSV" button!
Let me know what you think.

**Comment by omega3** [comment]
I like it. This is what I wanted. This is great because everyone can decide what to edit and what to import to Anki. Great job.

But I noticed that if you take as an example headword people, for sentence:
"The hotel was full of business people." the content of column "Form" is shortened to "theatre/business etc people" while in dictionary is "theatre/business etc people (=people who work or are involved in the theatre etc)"

Also take for example headword "home" and check sentence "A family of birds made their home under the roof." and the output in column "Form". 
The output lacks: "work from/at home (=do your work at home instead of at a company office)" and "(=started living)"

Can you fix the content of this column, please?

By the way, can you tell me how many headwords can this site process in one go? 
10, 100 or 1000?

**Comment by yakhinvadim** [comment]
Hey, sorry for the late response. Also, thank you for the feedback, I really appreciate it.

1) About (=...) part in examples and forms.
I intentionally remove this part from examples and forms. See, cards look like this:
```
Example

Form
------
Definition
```


Each part has it's own role here:

```
Example (here is the sentence you need to understand)

Form (here is the specific part of the sentence you need to understand)
------
Definition (here is what this part means in this sentence)
```

Now, the (=...) part in Form or Example is kind of a definition, so it gives the answer to the question *in the question*.

That's why I remove it.

I understand that you want to create your own kinds of cards with csv, so I guess it would make sense to have an unshortened form in csv.
I guess, I will create a separate issue for that, but I don't think I'll do it soon since I have some issues with a higher priority (like downloading sound).
But if you are familiar with JavaScript I would be happy to give you some guidance on how to implement this.

2) About the number of processed headwords at once.

I don't know. I've never tested it with 100+ requests at once. I think it should handle up to 100 requests at once with no problem, but anything higher can work poorly. There is no exact number since it highly depends on the machine you're opening the website with and the number of examples in each word. Also, ldoce website can stop responding to longman-to-anki if it sends too many requests at once, but I never faced this issue.

**Comment by omega3** [comment]
When creating a card a lot of different templates can be created and users will make it in accordance with their own preferences, anyway. When importing to Anki it is possible to change order of Fields, I mean to assign a column to Anki field.

In many cases a manual editing of cards is necessary. 

My typical card would look like this:

Front template (question):

```
partOfSpeech

My native language translation of headword or in some cases of a whole sentence. 

_Example sentence changed to close:_
The hotel was full of {{c1::business people}}.
```

Back template (Answer):

```
Repeated Front (which means full sentence is displayed).

The hotel was full of business people.

headword
pronunciation 
frequency 
definition 
form

2 PEOPLE IN GENERAL [plural] people in general, or people other than yourself

theatre/business etc people (=people who work or are involved in the theatre etc)
```

Form is for me an extra information and I don't put it in Front (question) because in many cases it has the content the same as headword that I want to recall (in this case I don't want to see word: _people_  in Front (Question), regardless of where it comes from: headword, form, definition, sentence. I will have my native translation in Front and I will learn to translate it into English.

Ok, you decide, but my approach is that it is easier to edit and remove unwanted content (even during learning phase) than add it manually, because to add it manually I need to search in dictionary. 

But in case of headword: _people_ you just shortened form to "_theatre/business etc people_" from original "_theatre/business etc people (=people who work or are involved in the theatre etc)_". Frankly, I don't see a profit in this action.

Also in case of a sentence: "_A family of birds made their home (=started living) under the roof._" I don't see a profit from removing "_(=started living)_".

I think the more information the better because users will have many, many approaches to how they want to design their cards.

Don't you use your native translation while learning English?

I will use google sheets for this:
https://blog.artofmemory.com/vocabulary-flashcards-google-translate-anki-4561.html
