### ISSUE TITLE
spaces -> tabs

### ISSUE THREAD

**Issue by yakhinvadim** [yakhinvadim/longman-to-anki#67]

**Comment by iamstarkov** [comment]
![](https://media2.giphy.com/media/sMR1xd3JCLo8E/giphy.gif)

**Comment by yakhinvadim** [comment]
@iamstarkov you just don't understand...

**Comment by yakhinvadim** [comment]
Proudly fixed 
![](http://gifsec.com/wp-content/uploads/GIF/2014/12/chuffed-happy-James-Gandolfini-proud-GIF.gif)
